### ISSUE TITLE
Add Radarr webhook extras

### ISSUE THREAD

**Issue by trueChazza** [midarrlabs/midarr-server#322]
The Radarr webhook currently only accounts for **On Import**

This issue is to enable the following additional notification triggers, to improve cache sync:

- On Movie Delete
- On Movie File Delete
- On Movie File Delete For Upgrade

![Image](https://user-images.githubusercontent.com/20368025/227702907-240e579d-670d-4e91-a61d-881517af68e6.png)

**Comment by onedr0p** [comment]
@trueChazza Should these webhooks be added automatically by Midarr? The docs make it seem that way:

> On server startup Midarr attempts to auto configure your integrations by:
> Adding webhook / connect endpoints. This is for keeping your cache in sync

However I don't see any added in the Connect sections of Sonarr or Radarr

**Comment by trueChazza** [comment]
Interesting, thanks for reporting. I'll try a fresh install on my end and report back. There should at least be some logs saying it's attempted to do it.

**Comment by trueChazza** [comment]
https://github.com/midarrlabs/midarr-server/blob/feature/v3.0.0/lib/media_server/application.ex#L24

This is the "job" that auto starts with the application, and attempts to auto configure the webhook / connect endpoint in Radarr. It must be failing to start for some reason? I'll investigate.

**Comment by trueChazza** [comment]
> @trueChazza Should these webhooks be added automatically by Midarr? The docs make it seem that way:
> 
> > On server startup Midarr attempts to auto configure your integrations by:
> > Adding webhook / connect endpoints. This is for keeping your cache in sync
> 
> However I don't see any added in the Connect sections of Sonarr or Radarr, also I don't see anything in the Midarr logs related to this action...

Oh and yes it should be added automatically by Midarr.

**Comment by onedr0p** [comment]
Here are my logs if it helps:

```
midarr-5d5fb9db89-r4jfq midarr Resolving Hex dependencies...
midarr-5d5fb9db89-r4jfq midarr Resolution completed in 0.313s
midarr-5d5fb9db89-r4jfq midarr Unchanged:
midarr-5d5fb9db89-r4jfq midarr   bcrypt_elixir 3.0.1
midarr-5d5fb9db89-r4jfq midarr   castore 1.0.1
midarr-5d5fb9db89-r4jfq midarr   certifi 2.9.0
midarr-5d5fb9db89-r4jfq midarr   comeonin 5.3.3
midarr-5d5fb9db89-r4jfq midarr   connection 1.1.0
midarr-5d5fb9db89-r4jfq midarr   cors_plug 3.0.3
midarr-5d5fb9db89-r4jfq midarr   cowboy 2.9.0
midarr-5d5fb9db89-r4jfq midarr   cowboy_telemetry 0.4.0
midarr-5d5fb9db89-r4jfq midarr   cowlib 2.11.0
midarr-5d5fb9db89-r4jfq midarr   db_connection 2.4.3
midarr-5d5fb9db89-r4jfq midarr   decimal 2.0.0
midarr-5d5fb9db89-r4jfq midarr   ecto 3.9.4
midarr-5d5fb9db89-r4jfq midarr   ecto_sql 3.9.2
midarr-5d5fb9db89-r4jfq midarr   elixir_make 0.7.6
midarr-5d5fb9db89-r4jfq midarr   esbuild 0.6.1
midarr-5d5fb9db89-r4jfq midarr   excoveralls 0.16.0
midarr-5d5fb9db89-r4jfq midarr   exile 0.1.0
midarr-5d5fb9db89-r4jfq midarr   expo 0.4.0
midarr-5d5fb9db89-r4jfq midarr   exstream 0.20.0
midarr-5d5fb9db89-r4jfq midarr   extaima 0.3.0
midarr-5d5fb9db89-r4jfq midarr   extitles 0.1.0
midarr-5d5fb9db89-r4jfq midarr   file_system 0.2.10
midarr-5d5fb9db89-r4jfq midarr   floki 0.34.2
midarr-5d5fb9db89-r4jfq midarr   gettext 0.22.1
midarr-5d5fb9db89-r4jfq midarr   hackney 1.18.1
midarr-5d5fb9db89-r4jfq midarr   httpoison 2.1.0
midarr-5d5fb9db89-r4jfq midarr   idna 6.1.1
midarr-5d5fb9db89-r4jfq midarr   jason 1.4.0
midarr-5d5fb9db89-r4jfq midarr   metrics 1.0.1
midarr-5d5fb9db89-r4jfq midarr   mime 2.0.3
midarr-5d5fb9db89-r4jfq midarr   mimerl 1.2.0
midarr-5d5fb9db89-r4jfq midarr   parse_trans 3.3.1
midarr-5d5fb9db89-r4jfq midarr   phoenix 1.6.16
midarr-5d5fb9db89-r4jfq midarr   phoenix_ecto 4.4.0
midarr-5d5fb9db89-r4jfq midarr   phoenix_html 3.3.1
midarr-5d5fb9db89-r4jfq midarr   phoenix_live_dashboard 0.7.2
midarr-5d5fb9db89-r4jfq midarr   phoenix_live_reload 1.4.1
midarr-5d5fb9db89-r4jfq midarr   phoenix_live_view 0.18.17
midarr-5d5fb9db89-r4jfq midarr   phoenix_pubsub 2.1.1
midarr-5d5fb9db89-r4jfq midarr   phoenix_template 1.0.1
midarr-5d5fb9db89-r4jfq midarr   phoenix_view 2.0.2
midarr-5d5fb9db89-r4jfq midarr   plug 1.14.2
midarr-5d5fb9db89-r4jfq midarr   plug_cowboy 2.6.1
midarr-5d5fb9db89-r4jfq midarr   plug_crypto 1.2.5
midarr-5d5fb9db89-r4jfq midarr   postgrex 0.16.5
midarr-5d5fb9db89-r4jfq midarr   ranch 1.8.0
midarr-5d5fb9db89-r4jfq midarr   scrivener 2.7.2
midarr-5d5fb9db89-r4jfq midarr   ssl_verify_fun 1.1.6
midarr-5d5fb9db89-r4jfq midarr   swoosh 1.9.1
midarr-5d5fb9db89-r4jfq midarr   tailwind 0.1.10
midarr-5d5fb9db89-r4jfq midarr   telemetry 1.2.1
midarr-5d5fb9db89-r4jfq midarr   telemetry_metrics 0.6.1
midarr-5d5fb9db89-r4jfq midarr   telemetry_poller 1.0.0
midarr-5d5fb9db89-r4jfq midarr   unicode_util_compat 0.7.0
midarr-5d5fb9db89-r4jfq midarr All dependencies are up to date
midarr-5d5fb9db89-r4jfq midarr psql: error: connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
midarr-5d5fb9db89-r4jfq midarr 	Is the server running locally and accepting connections on that socket?
midarr-5d5fb9db89-r4jfq midarr
midarr-5d5fb9db89-r4jfq midarr 20:20:16.354 [info] Migrations already up
midarr-5d5fb9db89-r4jfq midarr ** (Ecto.ConstraintError) constraint error when attempting to insert struct:
midarr-5d5fb9db89-r4jfq midarr
midarr-5d5fb9db89-r4jfq midarr     * media_types_type_index (unique_constraint)
midarr-5d5fb9db89-r4jfq midarr
midarr-5d5fb9db89-r4jfq midarr If you would like to stop this constraint violation from raising an
midarr-5d5fb9db89-r4jfq midarr exception and instead add it as an error to your changeset, please
midarr-5d5fb9db89-r4jfq midarr call `unique_constraint/3` on your changeset with the constraint
midarr-5d5fb9db89-r4jfq midarr `:name` as an option.
midarr-5d5fb9db89-r4jfq midarr
midarr-5d5fb9db89-r4jfq midarr The changeset has not defined any constraint.
midarr-5d5fb9db89-r4jfq midarr
midarr-5d5fb9db89-r4jfq midarr     (ecto 3.9.4) lib/ecto/repo/schema.ex:795: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
midarr-5d5fb9db89-r4jfq midarr     (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
midarr-5d5fb9db89-r4jfq midarr     (ecto 3.9.4) lib/ecto/repo/schema.ex:780: Ecto.Repo.Schema.constraints_to_errors/3
midarr-5d5fb9db89-r4jfq midarr     (ecto 3.9.4) lib/ecto/repo/schema.ex:761: Ecto.Repo.Schema.apply/4
midarr-5d5fb9db89-r4jfq midarr     (ecto 3.9.4) lib/ecto/repo/schema.ex:369: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
midarr-5d5fb9db89-r4jfq midarr     priv/repo/seeds.exs:15: (file)
midarr-5d5fb9db89-r4jfq midarr Database midarr ready
midarr-5d5fb9db89-r4jfq midarr 20:20:20.159 [info] Running MediaServerWeb.Endpoint with cowboy 2.9.0 at :::4000 (http)
midarr-5d5fb9db89-r4jfq midarr 20:20:20.173 [info] Access MediaServerWeb.Endpoint at http://localhost:4000
```

**Comment by trueChazza** [comment]
Thanks for that. Yeah I can't see any mention of the webhook.

- What Midarr version are you using?
- What Radarr version are you using?

**Comment by onedr0p** [comment]
Midarr: 3.0.0 beta 9
Radarr: 4.4.2.6956
Sonarr: 4.0.0.419

**Comment by trueChazza** [comment]
I wonder if I provide an example default so these jobs don't fail. Then we can override them?
Alternatively, I'd need to detail it out better in the README - in the upcoming Gotchas section maybe.

What do you think?

**Comment by trueChazza** [comment]
> I wonder if I provide an example default so these jobs don't fail. Then we can override them?

Radarr / Sonarr both send a test POST when adding Connect endpoints, the URL must be valid. So this solution won't work.

**Comment by trueChazza** [comment]
Maybe just surfacing the error to the logs will be enough for now.

**Comment by onedr0p** [comment]
Yep that was it, I didn't have APP_URL set.
